#!/usr/bin/env bb
;; Synthetic Clojure tree generator for the tree-scale memory battery.
;;
;; Deterministic: the bytes written for a given (generator-version, N) are a
;; pure function of the file index. Re-running VERIFIES rather than assumes: every
;; promised file must exist with its exact byte count and content digest, no
;; unlisted file may be present, and the manifest digest (which covers contents,
;; not just paths and sizes) is rechecked against the bytes on disk. Mismatched
;; bytes regenerate; unexpected files refuse. Verifying all three trees costs
;; about 3 s, which is the price of a table that cannot print N=10,000 over a
;; corpus of 9,999 files.
;;
;; Layout, one project per scale so the CLI's build-file discovery finds it:
;;
;;   <root>/<N>/deps.edn
;;   <root>/<N>/src/membat/pkg<PPP>/mod<IIIII>.clj
;;   <root>/<N>/manifest.edn
;;
;; @spec MCP-OP-MEM-001
;;
;; Usage:
;;   bb bench/memory_battery/generate_tree.clj --root /home/forge/tmp/membat \
;;      --scales 100,1000,10000
;;   bb bench/memory_battery/generate_tree.clj --self-test

(ns generate-tree
  (:require
   [clojure.java.io :as io]
   [clojure.string :as str])
  (:import
   [java.nio.file Files LinkOption]))

(def generator-version "membat-gen-1")

;; Byte targets per size bucket. Chosen to sit under this repository's own
;; distribution (mean 17 KB, p50 10 KB) so the battery is not accused of being
;; tuned to fail: 60% ~1.5 KB, 30% ~5 KB, 10% ~15 KB, mean ~3.9 KB.
(def size-buckets
  {:small 1500 :medium 5000 :large 15000})

(defn bucket-for
  "Deterministic size bucket for file index i."
  [i]
  (let [r (mod i 10)]
    (cond (< r 6) :small
          (< r 9) :medium
          :else :large)))

(defn ns-name-for
  [i]
  (format "membat.pkg%03d.mod%05d" (quot i 100) i))

(defn rel-path-for
  [i]
  (format "src/membat/pkg%03d/mod%05d.clj" (quot i 100) i))

(defn- filler-form
  "One realistic-looking private helper, ~250 bytes."
  [i k]
  (format
    (str "(defn- step-%05d-%02d\n"
         "  \"Fold one %s record into the running accumulator.\"\n"
         "  [acc {:keys [id kind weight tags] :as record}]\n"
         "  (let [scaled (* (or weight 1) %d)]\n"
         "    (cond-> acc\n"
         "      (contains? tags :alpha) (update :alpha (fnil + 0) scaled)\n"
         "      (= kind :beta)          (update :beta (fnil conj []) id)\n"
         "      :always                 (assoc-in [:seen id] record))))\n\n")
    i k (ns-name-for i) (inc (mod (+ i k) 17))))

(defn file-source
  "Deterministic source text for file index i in a tree of `total` files."
  [i total]
  (let [nsname (ns-name-for i)
        dep-a (ns-name-for (mod (+ i 7) total))
        dep-b (ns-name-for (mod (+ i 31) total))
        header
        (format
          (str "(ns %s\n"
               "  \"Synthetic namespace %05d of %d, generated by %s.\"\n"
               "  (:require\n"
               "   [clojure.set :as set]\n"
               "   [clojure.string :as str]\n"
               "   [%s :as dep-a]\n"
               "   [%s :as dep-b]))\n\n"
               "(def ^:private defaults-%05d\n"
               "  {:id %d\n"
               "   :label \"mod-%05d\"\n"
               "   :tags #{:alpha :beta :gamma}\n"
               "   :retries 3\n"
               "   :timeout-ms %d})\n\n"
               "(defn- normalize-%05d\n"
               "  \"Merge caller options over the module defaults.\"\n"
               "  [options]\n"
               "  (merge defaults-%05d (select-keys options [:id :label :tags :retries])))\n\n"
               "(defn handle-%05d\n"
               "  \"Public entry point for module %05d.\"\n"
               "  [options records]\n"
               "  (let [config (normalize-%05d options)]\n"
               "    (reduce (fn [acc record]\n"
               "              (assoc acc (:id record) (str/upper-case (str (:label config)))))\n"
               "            {}\n"
               "            records)))\n\n"
               "(defmulti render-%05d\n"
               "  \"Dispatch on record kind.\"\n"
               "  :kind)\n\n"
               "(defmethod render-%05d :alpha [record]\n"
               "  (str \"alpha/\" (:id record) \"/\" (dep-a/handle-%05d {} [])))\n\n"
               "(defmethod render-%05d :beta [record]\n"
               "  (str \"beta/\" (:id record) \"/\" (dep-b/handle-%05d {} [])))\n\n"
               "(defmethod render-%05d :default [record]\n"
               "  (str \"other/\" (:id record)))\n\n"
               "(defn summarize-%05d\n"
               "  \"Set-union the tags across a record sequence.\"\n"
               "  [records]\n"
               "  (reduce set/union #{} (map :tags records)))\n\n")
          nsname i total generator-version
          dep-a dep-b
          i i i (+ 250 (* 13 (mod i 41)))
          i i
          i i i
          i i (mod (+ i 7) total)
          i (mod (+ i 31) total)
          i
          i)
        target (get size-buckets (bucket-for i))
        sb (StringBuilder. header)]
    (loop [k 0]
      (when (and (< (.length sb) target) (< k 200))
        (.append sb (filler-form i k))
        (recur (inc k))))
    (str sb)))

(def profiles
  "The corpus shapes the battery measures. `:default` is the representative
  small/medium Clojure tree; the other three are the adversarial shapes Sol
  named as cheap and missing.

  Each is a SEPARATE ARM, not a variation folded into the default tree, because
  an operation can be bounded over 10,000 ordinary files and unbounded over one
  pathological one — averaging them together hides exactly the case worth
  measuring."
  {:default {:extension "clj"
             :note "representative small/medium Clojure sources, mean ~4 KB"}
   :cljc    {:extension "cljc"
             :note (str "reader conditionals: #? and #?@ in requires and in "
                        "forms, so every platform branch is parsed and carried")}
   :giant   {:extension "clj"
             :note "ONE ~1.9 MiB source file — the per-file, not per-tree, case"}
   :nested  {:extension "clj"
             :note (str "ONE adversarial file: ~300-deep nesting plus a "
                        "token-dense literal, so node count dwarfs byte count")}})

(def profile-arms
  "The adversarial arms built beside the default trees, as [profile n]. MUST
  agree with clj-surgeon.memory-battery/extra-corpus-arms; the self-test loads
  both and compares them so the two lists cannot drift apart silently."
  [[:cljc 100] [:giant 1] [:nested 1]])

(def ^:private giant-target-bytes 1992294)   ; 1.9 MiB
(def ^:private nesting-depth 300)
(def ^:private dense-token-count 20000)

(defn tree-dir-name
  "Directory under the corpus root for one (profile, N). The default profile
  keeps its bare `<N>` name so existing corpora and receipts stay readable."
  [profile n]
  (if (= :default profile) (str n) (str (name profile) "-" n)))

(defn rel-path-for-profile
  [profile i]
  (case profile
    :default (rel-path-for i)
    :cljc (format "src/membat/pkg%03d/mod%05d.cljc" (quot i 100) i)
    :giant "src/membat/giant.clj"
    :nested "src/membat/nested.clj"))

(defn- cljc-file-source
  "A .cljc whose every form carries a platform branch."
  [i total]
  (let [nsname (ns-name-for i)
        dep-a (ns-name-for (mod (+ i 7) total))]
    (format
      (str "(ns %s\n"
           "  \"Synthetic reader-conditional namespace %05d of %d.\"\n"
           "  (:require\n"
           "   [clojure.string :as str]\n"
           "   #?(:clj [clojure.set :as set]\n"
           "      :cljs [clojure.set :as set])\n"
           "   [%s :as dep-a]))\n\n"
           "(def ^:private platform-%05d\n"
           "  #?(:clj :jvm :cljs :browser :default :unknown))\n\n"
           "(defn handle-%05d\n"
           "  \"Public entry point for module %05d.\"\n"
           "  [options]\n"
           "  #?(:clj  (assoc options :on :jvm :id %d)\n"
           "     :cljs (assoc options :on :js  :id %d)))\n\n"
           "#?@(:clj [(def ^:private jvm-only-%05d {:id %d})\n"
           "          (defn jvm-handle-%05d [] (dep-a/handle-%05d {} []))]\n"
           "    :cljs [(def ^:private js-only-%05d {:id %d})])\n\n"
           "(defn summarize-%05d\n"
           "  \"Set-union the tags across a record sequence.\"\n"
           "  [records]\n"
           "  (reduce set/union #{} (map :tags records)))\n\n")
      nsname i total dep-a
      i
      i i i i
      i i i (mod (+ i 7) total) i i
      i)))

(defn- giant-file-source
  "One namespace padded with ordinary forms to ~1.9 MiB."
  [_i _total]
  (let [sb (StringBuilder.
             (str "(ns membat.giant\n"
                  "  \"One ~1.9 MiB synthetic source file.\"\n"
                  "  (:require [clojure.string :as str]))\n\n"))]
    (loop [k 0]
      (when (< (.length sb) giant-target-bytes)
        ;; distinct name per form, so the file is one large realistic namespace
        ;; rather than the same defn repeated thousands of times
        (.append sb (filler-form (quot k 100) (mod k 100)))
        (recur (inc k))))
    (str sb)))

(defn- nested-file-source
  "One adversarial file: a ~300-deep tower plus a token-dense literal. Node
  count, not byte count, is what this arm stresses."
  [_i _total]
  (str "(ns membat.nested\n"
       "  \"Adversarial shape: deep nesting and token density in a small file.\")\n\n"
       "(def tower\n  "
       (apply str (repeat nesting-depth "{:k ["))
       ":leaf"
       (apply str (repeat nesting-depth "]}"))
       ")\n\n"
       "(def dense\n  ["
       (str/join " " (range dense-token-count))
       "])\n\n"
       "(defn depth [x]\n"
       "  (if (map? x) (inc (depth (first (:k x)))) 0))\n"))

(defn source-for
  "Deterministic source text for one file of one profile."
  [profile i total]
  (case profile
    :default (file-source i total)
    :cljc (cljc-file-source i total)
    :giant (giant-file-source i total)
    :nested (nested-file-source i total)))

(defn- sha256-hex
  [^String s]
  (let [md (java.security.MessageDigest/getInstance "SHA-256")]
    (->> (.digest md (.getBytes s "UTF-8"))
         (map #(format "%02x" %))
         (apply str))))

(defn- file-sha256-hex
  "Digest of the bytes actually on disk — never of what a manifest says is there."
  [f]
  (let [md (java.security.MessageDigest/getInstance "SHA-256")
        buf (byte-array 65536)]
    (with-open [in (io/input-stream f)]
      (loop []
        (let [read (.read in buf)]
          (when (pos? read)
            (.update md buf 0 read)
            (recur)))))
    (apply str (map #(format "%02x" %) (.digest md)))))

(defn- deps-edn-text []
  "{:paths [\"src\"]\n :deps {org.clojure/clojure {:mvn/version \"1.12.1\"}}}\n")

(defn expected-entries
  "The corpus the generator promises for (profile, n), as
  [rel bytes content-sha]. Derived from `source-for`, which is deterministic, so
  no per-file digest has to be stored anywhere for a later run to check bytes."
  ([n] (expected-entries :default n))
  ([profile n]
   (mapv (fn [i]
           (let [text (source-for profile i n)]
             [(rel-path-for-profile profile i)
              (count (.getBytes ^String text "UTF-8"))
              (sha256-hex text)]))
         (range n))))

(defn entries-digest
  "Manifest digest over path, size AND content. The old path+size digest could
  not distinguish two different corpora of the same shape."
  [entries]
  (sha256-hex (str/join "\n" (map (fn [[rel size sha]] (str rel ":" size ":" sha))
                                  (sort-by first entries)))))

(defn- actual-source-files
  "Every regular file under the tree's src/, as tree-relative paths."
  [dir]
  (let [src (io/file dir "src")
        prefix (str (.getPath (io/file dir)) "/")]
    (when (.isDirectory src)
      (into #{}
            (comp (filter #(.isFile ^java.io.File %))
                  (map #(str/replace (.getPath ^java.io.File %) prefix "")))
            (file-seq src)))))

(defn verify-tree
  "Check the corpus on disk against what the generator promises for `n`.

  Returns {:status :ok}, {:status :regenerate :reason ... :detail ...} when the
  bytes are missing or wrong, or {:status :refuse :reason :unexpected-files ...}
  when the tree holds files the generator never wrote — regenerating would not
  remove those, and deleting files under MEMBAT_ROOT on the corpus's own say-so
  is worse than stopping.

  This exists because the previous no-op checked only :generator-version, :n and
  the manifest's own claimed file count, so one deleted file could let a table
  print N=10,000 over 9,999 files."
  ([root n] (verify-tree root :default n))
  ([root profile n]
  (let [dir (io/file root (tree-dir-name profile n))
        manifest-file (io/file dir "manifest.edn")
        existing (when (.exists manifest-file)
                   (try (read-string (slurp manifest-file)) (catch Exception _ nil)))
        expected (expected-entries profile n)
        expected-index (into {} (map (fn [[rel size sha]] [rel [size sha]])) expected)]
    (cond
      (nil? existing)
      {:status :regenerate :reason :no-manifest :detail (str manifest-file)}

      (not= generator-version (:generator-version existing))
      {:status :regenerate :reason :generator-version
       :detail {:manifest (:generator-version existing) :expected generator-version}}

      (not= profile (:profile existing :default))
      {:status :regenerate :reason :wrong-profile
       :detail {:manifest (:profile existing) :expected profile}}

      (not= n (:n existing))
      {:status :regenerate :reason :wrong-n
       :detail {:manifest (:n existing) :expected n}}

      (not (.exists (io/file dir "deps.edn")))
      {:status :regenerate :reason :missing-file :detail "deps.edn"}

      :else
      (let [actual (or (actual-source-files dir) #{})
            extras (sort (remove expected-index actual))]
        (if (seq extras)
          {:status :refuse :reason :unexpected-files
           :detail {:count (count extras) :sample (vec (take 5 extras))}}
          (or
            ;; Every promised file: present, right size, right bytes.
            (reduce
              (fn [_ [rel size sha]]
                (let [f (io/file dir rel)]
                  (cond
                    ;; A symlink at an expected path is refused outright, never
                    ;; regenerated: `.isFile`/`.length`/reading through it all
                    ;; follow the link, so a symlink to an out-of-tree copy with
                    ;; identical bytes would otherwise verify clean.
                    (Files/isSymbolicLink (.toPath f))
                    (reduced {:status :refuse :reason :symlink-at-expected-path
                              :detail rel})

                    ;; A directory at an expected path must never fall through
                    ;; to :missing-file/:regenerate: writing the promised bytes
                    ;; would then throw the JVM's own untyped
                    ;; FileNotFoundException ("Is a directory") mid-spit,
                    ;; instead of a typed refusal raised before any write.
                    (.isDirectory f)
                    (reduced {:status :refuse :reason :directory-at-expected-path
                              :detail rel})

                    ;; `Files/isRegularFile` with NOFOLLOW_LINKS, not `.isFile`
                    ;; (which follows symlinks) — the symlink case above is
                    ;; already handled, so anything left that isn't a real
                    ;; regular file is either missing or some other node type.
                    (not (Files/isRegularFile (.toPath f)
                                              (into-array LinkOption [LinkOption/NOFOLLOW_LINKS])))
                    (reduced {:status :regenerate :reason :missing-file :detail rel})

                    (not= (long size) (.length f))
                    (reduced {:status :regenerate :reason :size-mismatch
                              :detail {:file rel :expected size :found (.length f)}})

                    (not= sha (file-sha256-hex f))
                    (reduced {:status :regenerate :reason :content-mismatch
                              :detail rel})

                    :else nil)))
              nil
              expected)
            ;; ...and the manifest's own claims, rechecked against those bytes.
            (when (not= (count expected) (:files existing))
              {:status :regenerate :reason :file-count-mismatch
               :detail {:manifest (:files existing) :expected (count expected)}})
            (when (not= (entries-digest expected) (:digest existing))
              {:status :regenerate :reason :digest-mismatch
               :detail {:manifest (:digest existing)
                        :expected (entries-digest expected)}})
            {:status :ok})))))))

(def ^:private allowed-root-prefix
  "MEMBAT_ROOT must resolve inside this directory unless the caller sets
  MEMBAT_ALLOW_ANY_ROOT=1. It is arbitrary and, without a marker, a fresh run
  would create or write into whatever it pointed at."
  "/home/forge/tmp")

(defn- membat-root-marker [root] (io/file root ".membat-root"))

(defn ensure-root-marker!
  "Guard MEMBAT_ROOT against pointing at an arbitrary directory: a FRESH root
  (does not yet exist) is created and marked; a root that already exists
  WITHOUT the marker is refused rather than written into — it might be $HOME,
  a real repository, or another tool's directory, and the battery has no way
  to tell. The root's canonical path must also resolve inside
  `allowed-root-prefix` unless `allow-any-root?` (default: the
  MEMBAT_ALLOW_ANY_ROOT=1 env var) says otherwise.

  Throws ex-info shaped like `verify-tree`'s :refuse ({:reason ... :detail
  ...}) so -main's existing REFUSED handler catches it uniformly. Returns nil."
  ([root] (ensure-root-marker! root (= "1" (System/getenv "MEMBAT_ALLOW_ANY_ROOT"))))
  ([root allow-any-root?]
   (let [rf (io/file root)
         canonical (.getCanonicalPath rf)
         allowed (.getCanonicalPath (io/file allowed-root-prefix))]
     (when (and (not allow-any-root?)
                (not (or (= canonical allowed)
                        (str/starts-with? canonical (str allowed java.io.File/separator)))))
       (throw (ex-info (str "MEMBAT_ROOT resolves outside " allowed-root-prefix
                            ": " canonical)
                       {:reason :membat-root-outside-allowed
                        :root root :resolved canonical :allowed allowed-root-prefix
                        :remedy "point MEMBAT_ROOT under /home/forge/tmp, or set MEMBAT_ALLOW_ANY_ROOT=1"})))
     (if (.exists rf)
       (when-not (.exists (membat-root-marker rf))
         (throw (ex-info (str "MEMBAT_ROOT exists without its marker: " root)
                         {:reason :membat-root-unmarked
                          :root root
                          :remedy (str "point MEMBAT_ROOT at a fresh directory, "
                                      "or create " (str (membat-root-marker rf))
                                      " yourself if you are certain this root "
                                      "was built by the battery")})))
       (.mkdirs rf))
     (when-not (.exists (membat-root-marker rf))
       (spit (membat-root-marker rf)
             (str "membat root created " (java.time.Instant/now) "\n"))))))

(defn generate-tree!
  "Write (or verify) the N-file tree under `root`. Returns the manifest.

  The reuse path is only taken when `verify-tree` has confirmed the bytes on
  disk; a corpus that does not match its promise is rewritten, and one carrying
  files the generator never wrote is refused by throwing."
  ([root n] (generate-tree! root :default n))
  ([root profile n]
  (let [dir (io/file root (tree-dir-name profile n))
        manifest-file (io/file dir "manifest.edn")
        check (verify-tree root profile n)]
    (case (:status check)
      :refuse
      (throw (ex-info (str "corpus at " dir " holds files the generator never wrote")
                      (assoc check :root root :n n
                             :remedy "remove them, or point MEMBAT_ROOT elsewhere")))

      :ok
      (assoc (read-string (slurp manifest-file)) :reused true)

      (do
        (.mkdirs dir)
        (spit (io/file dir "deps.edn") (deps-edn-text))
        (let [entries (expected-entries profile n)
              _ (doseq [[i [rel _ _]] (map-indexed vector entries)]
                  (let [f (io/file dir rel)]
                    (.mkdirs (.getParentFile f))
                    (spit f (source-for profile i n))))
              total-bytes (reduce + 0 (map second entries))
              manifest {:generator-version generator-version
                        :profile profile
                        :n n
                        :files (count entries)
                        :bytes total-bytes
                        :mean-file-bytes (long (/ total-bytes (max 1 (count entries))))
                        :largest-file-bytes (apply max 0 (map second entries))
                        :digest (entries-digest entries)
                        :verified-reason (:reason check)
                        :reused false}]
          (spit manifest-file (pr-str manifest))
          manifest))))))

;; ------------------------------------------------------------------

(defn- parse-args
  [args]
  (loop [a args acc {:root (or (System/getenv "MEMBAT_ROOT") "/home/forge/tmp/membat")
                     :scales [100 1000 10000]}]
    (if-let [x (first a)]
      (case x
        "--root" (recur (drop 2 a) (assoc acc :root (second a)))
        "--scales" (recur (drop 2 a)
                          (assoc acc :scales
                                 (mapv #(Long/parseLong %)
                                       (str/split (second a) #","))))
        "--self-test" (recur (rest a) (assoc acc :self-test true))
        (recur (rest a) acc))
      acc)))

(defn- rm-rf! [f]
  (let [f (io/file f)]
    (when (.exists f)
      (when (.isDirectory f)
        (doseq [c (.listFiles f)] (rm-rf! c)))
      (.delete f))))

;; The no-op path is the one that can lie: it decides, without looking at the
;; corpus, that a table may print N=10,000. These assertions drive it against a
;; real three-file tree on disk.
(defn- verification-self-test! []
  (let [root (str (io/file (System/getProperty "java.io.tmpdir")
                           (str "membat-selftest-" (System/currentTimeMillis))))
        dir (io/file root "3")
        victim (io/file dir (rel-path-for 1))]
    (try
      (let [fresh (generate-tree! root 3)]
        (assert (false? (:reused fresh)) "first build generates")
        (assert (= 3 (:files fresh)) "three files written")
        (assert (= :ok (:status (verify-tree root 3)))
                "a tree that was just written verifies")
        (assert (true? (:reused (generate-tree! root 3)))
                "an intact tree is a no-op"))

      ;; A DELETED file must never be reported as present.
      (.delete victim)
      (assert (= :regenerate (:status (verify-tree root 3)))
              "a missing corpus file is detected, not trusted")
      (assert (= :missing-file (:reason (verify-tree root 3))))
      (assert (false? (:reused (generate-tree! root 3)))
              "a missing corpus file regenerates the tree")
      (assert (.exists victim) "regeneration restores the deleted file")

      ;; MODIFIED content must never pass on its byte count alone.
      (spit victim (str/replace (slurp victim) "defn-" "defn+"))
      (assert (= :content-mismatch (:reason (verify-tree root 3)))
              "same size, different bytes is caught by the content digest")
      (generate-tree! root 3)
      (assert (= :ok (:status (verify-tree root 3))))

      ;; EXTRA files are refused, not regenerated: regeneration would not remove
      ;; them, so it would loop, and deleting files under MEMBAT_ROOT is worse.
      (spit (io/file dir "src/membat/pkg000/intruder.clj") "(ns membat.intruder)")
      (assert (= :refuse (:status (verify-tree root 3)))
              "an unlisted file in the corpus is a refusal")
      (assert (= :unexpected-files (:reason (verify-tree root 3))))
      (.delete (io/file dir "src/membat/pkg000/intruder.clj"))

      ;; A SYMLINK at an expected path, even pointing at bytes identical to
      ;; the promised content, must never be reported as present: `.isFile`
      ;; follows symlinks, so a symlink to an out-of-tree copy of the same
      ;; file used to verify clean.
      (let [victim2 (io/file dir (rel-path-for 2))
            outside (io/file root "outside-target.clj")]
        (spit outside (slurp victim2))
        (.delete victim2)
        (Files/createSymbolicLink (.toPath victim2) (.toPath outside)
                                  (make-array java.nio.file.attribute.FileAttribute 0))
        (assert (= :refuse (:status (verify-tree root 3)))
                "a symlink at an expected path is refused, not verified")
        (assert (= :symlink-at-expected-path (:reason (verify-tree root 3))))
        (Files/delete (.toPath victim2))
        (generate-tree! root 3)
        (assert (= :ok (:status (verify-tree root 3)))
                "regeneration restores a plain file after the symlink is removed"))

      ;; A DIRECTORY at an expected path must be a typed refusal raised BEFORE
      ;; any write, not an untyped FileNotFoundException thrown mid-spit.
      (let [victim3 (io/file dir (rel-path-for 0))]
        (.delete victim3)
        (.mkdirs victim3)
        (assert (= :refuse (:status (verify-tree root 3)))
                "a directory at an expected path is refused, not silently missing")
        (assert (= :directory-at-expected-path (:reason (verify-tree root 3))))
        ;; generate-tree! must refuse the same way, typed, and must not throw
        ;; the JVM's own untyped "Is a directory" I/O exception.
        (let [threw (try (generate-tree! root 3) :did-not-throw
                         (catch clojure.lang.ExceptionInfo e
                           (:reason (ex-data e)))
                         (catch Exception e
                           [:untyped (class e)]))]
          (assert (= :directory-at-expected-path threw)
                  (str "generate-tree! refuses typed, not: " (pr-str threw))))
        (.delete victim3)
        (generate-tree! root 3)
        (assert (= :ok (:status (verify-tree root 3)))
                "regeneration restores a plain file after the directory is removed"))

      ;; A TAMPERED manifest digest is not authority over the bytes.
      (let [mf (io/file dir "manifest.edn")]
        (spit mf (pr-str (assoc (read-string (slurp mf)) :digest "deadbeef")))
        (assert (= :digest-mismatch (:reason (verify-tree root 3)))
                "the manifest digest is rechecked against the actual bytes"))
      ;; Every adversarial arm builds, verifies, and reuses — and is the shape
      ;; it claims to be. These are separate corpora, so each gets its own
      ;; directory and its own manifest.
      (doseq [[profile n] profile-arms]
        (let [m (generate-tree! root profile n)]
          (assert (false? (:reused m)) (str profile " builds"))
          (assert (= n (:files m)) (str profile " file count"))
          (assert (= profile (:profile m)) (str profile " is recorded"))
          (assert (= :ok (:status (verify-tree root profile n)))
                  (str profile " verifies"))
          (assert (true? (:reused (generate-tree! root profile n)))
                  (str profile " reuses"))
          (assert (.isDirectory (io/file root (tree-dir-name profile n)))
                  (str profile " has its own corpus directory"))))

      (let [cljc (slurp (io/file root (tree-dir-name :cljc 100)
                                  (rel-path-for-profile :cljc 3)))
            giant (io/file root (tree-dir-name :giant 1)
                           (rel-path-for-profile :giant 0))
            nested (slurp (io/file root (tree-dir-name :nested 1)
                                   (rel-path-for-profile :nested 0)))]
        (assert (str/includes? cljc "#?(:clj") "cljc carries reader conditionals")
        (assert (str/includes? cljc "#?@(:clj") "cljc carries splicing conditionals")
        (assert (str/ends-with? (.getName giant) ".clj"))
        (assert (>= (.length giant) 1900000)
                (str "the giant arm is ~1.9 MiB, got " (.length giant)))
        (assert (= nesting-depth (count (re-seq #"\{:k \[" nested)))
                "the nested arm reaches its stated depth")
        (assert (str/includes? nested "(def dense") "the nested arm is token-dense")
        (assert (< (count nested) 200000)
                "the nested arm stresses node count, not byte count"))

      (println "generate_tree verification self-test: ok")
      (finally (rm-rf! root)))))

;; MEMBAT_ROOT is arbitrary and, before this, had no marker or scope guard: a
;; fresh root auto-created whatever it pointed at, and a shared/pre-existing
;; directory (potentially unrelated to the battery) was written into on the
;; same footing as a battery-owned one.
(defn- root-marker-self-test! []
  (let [base "/home/forge/tmp"
        stamp (System/currentTimeMillis)
        fresh-root (io/file base (str "membat-marker-selftest-" stamp))
        unmarked-root (io/file base (str "membat-unmarked-selftest-" stamp))
        outside-root (io/file (System/getProperty "java.io.tmpdir")
                              (str "membat-outside-selftest-" stamp))]
    (try
      ;; A fresh root is created and marked by the battery itself.
      (ensure-root-marker! (str fresh-root))
      (assert (.isDirectory fresh-root) "a fresh root is created")
      (assert (.exists (io/file fresh-root ".membat-root"))
              "a fresh root is marked")
      ;; Reusing an already-marked root is a no-op, not a refusal.
      (ensure-root-marker! (str fresh-root))

      ;; A pre-existing root with NO marker is refused, not silently adopted
      ;; — it might be $HOME, a real repo, or another tool's directory.
      (.mkdirs unmarked-root)
      (let [reason (try (ensure-root-marker! (str unmarked-root)) :did-not-throw
                        (catch clojure.lang.ExceptionInfo e (:reason (ex-data e))))]
        (assert (= :membat-root-unmarked reason)
                (str "an unmarked pre-existing root is refused, got " reason)))

      ;; A root outside /home/forge/tmp is refused by default...
      (let [reason (try (ensure-root-marker! (str outside-root) false) :did-not-throw
                        (catch clojure.lang.ExceptionInfo e (:reason (ex-data e))))]
        (assert (= :membat-root-outside-allowed reason)
                (str "a root outside the allowed scope is refused, got " reason)))
      (assert (not (.exists outside-root))
              "a refused outside-scope root is never created")

      ;; ...unless the caller explicitly opts in (MEMBAT_ALLOW_ANY_ROOT=1).
      (ensure-root-marker! (str outside-root) true)
      (assert (.isDirectory outside-root)
              "an explicit override creates and marks an outside-scope root")

      (println "generate_tree root-marker self-test: ok")
      (finally
        (rm-rf! fresh-root)
        (rm-rf! unmarked-root)
        (rm-rf! outside-root)))))

(defn- self-test! []
  (let [a (file-source 3 100)
        b (file-source 3 100)
        c (file-source 9 100)]
    (assert (= a b) "generator must be deterministic")
    (assert (not= a c) "different indices must produce different sources")
    (assert (str/includes? a "(ns membat.pkg000.mod00003") "ns form")
    (assert (str/includes? a "(defmethod render-00003 :alpha") "multimethod arm")
    (assert (>= (count c) (:large size-buckets)) "large bucket reaches its target")
    (assert (< (count a) (:medium size-buckets)) "small bucket stays small")
    (assert (= :small (bucket-for 0)))
    (assert (= :medium (bucket-for 6)))
    (assert (= :large (bucket-for 9)))
    (verification-self-test!)
    (root-marker-self-test!)
    (println "generate_tree self-test: ok")
    0))

(defn -main [& args]
  (let [{:keys [root scales self-test]} (parse-args args)]
    (if self-test
      (System/exit (self-test!))
      (do
        (try
          (ensure-root-marker! root)
          (catch clojure.lang.ExceptionInfo e
            (binding [*out* *err*]
              (println "REFUSED:" (.getMessage e))
              (println (pr-str (ex-data e))))
            (System/exit 2)))
        (doseq [[profile n] (into (vec (for [n (sort scales)] [:default n]))
                                  profile-arms)]
          (let [t0 (System/currentTimeMillis)
                m (try
                    (generate-tree! root profile n)
                    (catch clojure.lang.ExceptionInfo e
                      (binding [*out* *err*]
                        (println "REFUSED:" (.getMessage e))
                        (println (pr-str (ex-data e))))
                      (System/exit 2)))
                ms (- (System/currentTimeMillis) t0)]
            (println (format "%-10s files=%-7d bytes=%-11d mean=%-8d largest=%-8d %s (%d ms)"
                             (tree-dir-name profile n)
                             (:files m) (:bytes m) (:mean-file-bytes m)
                             (:largest-file-bytes m)
                             (if (:reused m)
                               "verified"
                               (str "generated:" (name (or (:verified-reason m)
                                                           :no-manifest))))
                             ms))))
        (System/exit 0)))))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
