#!/usr/bin/env bb
;; Synthetic Clojure tree generator for the tree-scale memory battery.
;;
;; Deterministic: the bytes written for a given (generator-version, N) are a
;; pure function of the file index. Re-running is a no-op once the manifest
;; matches, so `make memory-battery` is cheap after the first build.
;;
;; Layout, one project per scale so the CLI's build-file discovery finds it:
;;
;;   <root>/<N>/deps.edn
;;   <root>/<N>/src/membat/pkg<PPP>/mod<IIIII>.clj
;;   <root>/<N>/manifest.edn
;;
;; @spec MCP-OP-MEM-001
;;
;; Usage:
;;   bb bench/memory_battery/generate_tree.clj --root /home/forge/tmp/membat \
;;      --scales 100,1000,10000
;;   bb bench/memory_battery/generate_tree.clj --self-test

(ns generate-tree
  (:require
   [clojure.java.io :as io]
   [clojure.string :as str]))

(def generator-version "membat-gen-1")

;; Byte targets per size bucket. Chosen to sit under this repository's own
;; distribution (mean 17 KB, p50 10 KB) so the battery is not accused of being
;; tuned to fail: 60% ~1.5 KB, 30% ~5 KB, 10% ~15 KB, mean ~3.9 KB.
(def size-buckets
  {:small 1500 :medium 5000 :large 15000})

(defn bucket-for
  "Deterministic size bucket for file index i."
  [i]
  (let [r (mod i 10)]
    (cond (< r 6) :small
          (< r 9) :medium
          :else :large)))

(defn ns-name-for
  [i]
  (format "membat.pkg%03d.mod%05d" (quot i 100) i))

(defn rel-path-for
  [i]
  (format "src/membat/pkg%03d/mod%05d.clj" (quot i 100) i))

(defn- filler-form
  "One realistic-looking private helper, ~250 bytes."
  [i k]
  (format
    (str "(defn- step-%05d-%02d\n"
         "  \"Fold one %s record into the running accumulator.\"\n"
         "  [acc {:keys [id kind weight tags] :as record}]\n"
         "  (let [scaled (* (or weight 1) %d)]\n"
         "    (cond-> acc\n"
         "      (contains? tags :alpha) (update :alpha (fnil + 0) scaled)\n"
         "      (= kind :beta)          (update :beta (fnil conj []) id)\n"
         "      :always                 (assoc-in [:seen id] record))))\n\n")
    i k (ns-name-for i) (inc (mod (+ i k) 17))))

(defn file-source
  "Deterministic source text for file index i in a tree of `total` files."
  [i total]
  (let [nsname (ns-name-for i)
        dep-a (ns-name-for (mod (+ i 7) total))
        dep-b (ns-name-for (mod (+ i 31) total))
        header
        (format
          (str "(ns %s\n"
               "  \"Synthetic namespace %05d of %d, generated by %s.\"\n"
               "  (:require\n"
               "   [clojure.set :as set]\n"
               "   [clojure.string :as str]\n"
               "   [%s :as dep-a]\n"
               "   [%s :as dep-b]))\n\n"
               "(def ^:private defaults-%05d\n"
               "  {:id %d\n"
               "   :label \"mod-%05d\"\n"
               "   :tags #{:alpha :beta :gamma}\n"
               "   :retries 3\n"
               "   :timeout-ms %d})\n\n"
               "(defn- normalize-%05d\n"
               "  \"Merge caller options over the module defaults.\"\n"
               "  [options]\n"
               "  (merge defaults-%05d (select-keys options [:id :label :tags :retries])))\n\n"
               "(defn handle-%05d\n"
               "  \"Public entry point for module %05d.\"\n"
               "  [options records]\n"
               "  (let [config (normalize-%05d options)]\n"
               "    (reduce (fn [acc record]\n"
               "              (assoc acc (:id record) (str/upper-case (str (:label config)))))\n"
               "            {}\n"
               "            records)))\n\n"
               "(defmulti render-%05d\n"
               "  \"Dispatch on record kind.\"\n"
               "  :kind)\n\n"
               "(defmethod render-%05d :alpha [record]\n"
               "  (str \"alpha/\" (:id record) \"/\" (dep-a/handle-%05d {} [])))\n\n"
               "(defmethod render-%05d :beta [record]\n"
               "  (str \"beta/\" (:id record) \"/\" (dep-b/handle-%05d {} [])))\n\n"
               "(defmethod render-%05d :default [record]\n"
               "  (str \"other/\" (:id record)))\n\n"
               "(defn summarize-%05d\n"
               "  \"Set-union the tags across a record sequence.\"\n"
               "  [records]\n"
               "  (reduce set/union #{} (map :tags records)))\n\n")
          nsname i total generator-version
          dep-a dep-b
          i i i (+ 250 (* 13 (mod i 41)))
          i i
          i i i
          i i (mod (+ i 7) total)
          i (mod (+ i 31) total)
          i
          i)
        target (get size-buckets (bucket-for i))
        sb (StringBuilder. header)]
    (loop [k 0]
      (when (and (< (.length sb) target) (< k 200))
        (.append sb (filler-form i k))
        (recur (inc k))))
    (str sb)))

(defn- sha256-hex
  [^String s]
  (let [md (java.security.MessageDigest/getInstance "SHA-256")]
    (->> (.digest md (.getBytes s "UTF-8"))
         (map #(format "%02x" %))
         (apply str))))

(defn- deps-edn-text []
  "{:paths [\"src\"]\n :deps {org.clojure/clojure {:mvn/version \"1.12.1\"}}}\n")

(defn generate-tree!
  "Write (or verify) the N-file tree under `root`. Returns the manifest."
  [root n]
  (let [dir (io/file root (str n))
        manifest-file (io/file dir "manifest.edn")
        existing (when (.exists manifest-file)
                   (try (read-string (slurp manifest-file)) (catch Exception _ nil)))]
    (if (and existing
             (= generator-version (:generator-version existing))
             (= n (:n existing))
             (= n (:files existing)))
      (assoc existing :reused true)
      (do
        (.mkdirs dir)
        (spit (io/file dir "deps.edn") (deps-edn-text))
        (let [entries
              (doall
                (for [i (range n)
                      :let [rel (rel-path-for i)
                            f (io/file dir rel)
                            text (file-source i n)]]
                  (do
                    (.mkdirs (.getParentFile f))
                    (spit f text)
                    [rel (count (.getBytes ^String text "UTF-8"))])))
              total-bytes (reduce + 0 (map second entries))
              manifest {:generator-version generator-version
                        :n n
                        :files (count entries)
                        :bytes total-bytes
                        :mean-file-bytes (long (/ total-bytes (max 1 (count entries))))
                        :largest-file-bytes (apply max 0 (map second entries))
                        :digest (sha256-hex
                                  (str/join "\n" (map (fn [[rel size]]
                                                        (str rel ":" size))
                                                      (sort-by first entries))))
                        :reused false}]
          (spit manifest-file (pr-str manifest))
          manifest)))))

;; ------------------------------------------------------------------

(defn- parse-args
  [args]
  (loop [a args acc {:root (or (System/getenv "MEMBAT_ROOT") "/home/forge/tmp/membat")
                     :scales [100 1000 10000]}]
    (if-let [x (first a)]
      (case x
        "--root" (recur (drop 2 a) (assoc acc :root (second a)))
        "--scales" (recur (drop 2 a)
                          (assoc acc :scales
                                 (mapv #(Long/parseLong %)
                                       (str/split (second a) #","))))
        "--self-test" (recur (rest a) (assoc acc :self-test true))
        (recur (rest a) acc))
      acc)))

(defn- self-test! []
  (let [a (file-source 3 100)
        b (file-source 3 100)
        c (file-source 9 100)]
    (assert (= a b) "generator must be deterministic")
    (assert (not= a c) "different indices must produce different sources")
    (assert (str/includes? a "(ns membat.pkg000.mod00003") "ns form")
    (assert (str/includes? a "(defmethod render-00003 :alpha") "multimethod arm")
    (assert (>= (count c) (:large size-buckets)) "large bucket reaches its target")
    (assert (< (count a) (:medium size-buckets)) "small bucket stays small")
    (assert (= :small (bucket-for 0)))
    (assert (= :medium (bucket-for 6)))
    (assert (= :large (bucket-for 9)))
    (println "generate_tree self-test: ok")
    0))

(defn -main [& args]
  (let [{:keys [root scales self-test]} (parse-args args)]
    (if self-test
      (System/exit (self-test!))
      (do
        (doseq [n scales]
          (let [t0 (System/currentTimeMillis)
                m (generate-tree! root n)
                ms (- (System/currentTimeMillis) t0)]
            (println (format "%-8s files=%-7d bytes=%-11d mean=%-6d largest=%-7d %s (%d ms)"
                             (str n) (:files m) (:bytes m) (:mean-file-bytes m)
                             (:largest-file-bytes m)
                             (if (:reused m) "reused" "generated") ms))))
        (System/exit 0)))))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
